# Generated by Django 5.2.4 on 2025-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_windoworder_window_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='windoworder',
            name='glass_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
