# Generated by Django 5.2.4 on 2025-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_windoworder_glass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='windoworder',
            name='Height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='windoworder',
            name='Width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='windoworder',
            name='type',
            field=models.CharField(default='Double Pane', max_length=50),
        ),
    ]
