# Generated by Django 5.2.4 on 2025-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_windoworder_glass_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='glass_type',
            field=models.CharField(default='Standard', max_length=100),
        ),
    ]
