# Generated by Django 5.2.4 on 2025-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_window_glass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='windoworder',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
