# Generated by Django 5.2.4 on 2025-07-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WindowOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_type', models.CharField(choices=[('single-hung', 'Single Hung'), ('double-hung', 'Double Hung'), ('casement', 'Casement'), ('sliding', 'Sliding'), ('awning', 'Awning'), ('picture', 'Picture Window')], max_length=20)),
                ('material', models.CharField(choices=[('vinyl', 'Vinyl'), ('wood', 'Wood'), ('aluminum', 'Aluminum'), ('fiberglass', 'Fiberglass')], max_length=20)),
                ('width', models.FloatField(help_text='Width in inches')),
                ('height', models.FloatField(help_text='Height in inches')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='application.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
