# Generated by Django 5.2.4 on 2025-07-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_windoworder_height_windoworder_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windoworder',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='windoworder',
            name='Width',
        ),
    ]
