# Generated by Django 5.2.4 on 2025-07-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_windoworder_height_remove_windoworder_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windoworder',
            name='glass_type',
        ),
        migrations.RemoveField(
            model_name='windoworder',
            name='type',
        ),
    ]
