# Generated by Django 5.2.4 on 2025-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_windoworder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windoworder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
