# Generated by Django 5.2.4 on 2025-08-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_windoworder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='windoworder',
            name='customer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
